Features/94 backend
merpw/forum pull request #102
Opened 2023-08-06 19:17 UTC by bomanviktor

Draft pull request for #94 (backend).

Since we do not have "invitations" implemented, the `/api/users/id/follow` endpoint is not complete (trying to follow a private account will just return 2, and not do anything in DB).

Some concerns I have:

When unfollowing, I just delete the row from the `followers` table. But I see that this could pose some issues. But it works in the tests.

However, the tests are still very high, and for next issue we will probably do the tests first, and then do the handlers so that we can define functionality first and then do the handlers according to the desired functionality.

2023-08-06 19:41 UTC, maximihajlov commented
The associated branch for #94 is [features/94-add-followers-and-profile-privacy](https://github.com/merpw/forum/tree/features/94-add-followers-and-profile-privacy). It already contains frontend.

I think it's better to merge `features/94-backend`  to `features/94-add-followers-and-profile-privacy` like we already did with #97

2023-08-06 20:03 UTC, maximihajlov commented
I've rebased the base branch onto main, so now frontend has both privacy and avatars

![image](https://github.com/merpw/forum/assets/43277901/c049421c-806e-43ac-b9de-034cbac32b30)

It should be much easier to rebase your branch now.

2023-08-06 22:17 UTC, maximihajlov commented on backend/forum/handlers/me.go
> +		Avatar:    user.Avatar.String,
Avatar and Bio are already in `SafeUser`. There's no need to redefine them

2023-08-06 22:46 UTC, maximihajlov requested changes
Nice, the history is now much cleaner!

- Followed users don't get full user data of private users

It can be reproduced by making public account, following it, and then making it private.

https://github.com/merpw/forum/assets/43277901/90b5f9fb-ff3d-43d7-b6b0-13ed08d2307d

- `followStatus: 0` is sent to users which are not logged in. We use SSR for user profiles, so it's better to have `undefined` on server side instead

2023-08-06 22:46 UTC, maximihajlov commented on backend/forum/handlers/me.go
> +		Avatar:    user.Avatar.String,
Avatar and Bio are already in `SafeUser`. There's no need to redefine them

2023-08-06 22:46 UTC, maximihajlov commented on backend/forum/database/ops_users.go
> +	return privacy == 1
You used `1` instead of `Private` (probably because of import cycle problem). It's better to move enums for privacy and followers to `database/models`

2023-08-06 22:46 UTC, maximihajlov commented on backend/forum/handlers/utils.go
> +)
It's better to define type for privacy status. Something like this:

```go
type Card int

const (
	Spades Card = iota
	Diamond
	Heart
	Club
)
```

2023-08-06 22:46 UTC, maximihajlov commented on backend/forum/database/models.go
> +	Privacy   int
It's better to use enum type here.

2023-08-06 22:46 UTC, maximihajlov commented on backend/forum/handlers/auth.go
> +		Avatar    string `json:"avatar"`
Not sure about this refactoring. Now we have a completely different style for sign up validation and login validation. Implementing of validation on `*Handlers` is not a good idea either because `h.checkUserName` is not a handler. They are also stored in utils, which is a bit unexpected.

2023-08-07 08:55 UTC, bomanviktor commented
> * `followStatus: 0` is sent to users which are not logged in. We use SSR for user profiles, so it's better to have `undefined` on server side instead

Care to explain further what you mean by this?

2023-08-07 14:14 UTC, maximihajlov requested changes

2023-08-07 14:14 UTC, maximihajlov commented on backend/forum/handlers/users.go
> +	meId := h.getUserId(w, r)
There's no need to call `getUserId` again. It was already called in main handler and saved in context

https://github.com/merpw/forum/blob/c93891b754a76adf11d7dd372541cdb30d7cd4fc/backend/forum/handlers/me.go#L7-L11

2023-08-07 14:14 UTC, maximihajlov commented on backend/forum/handlers/users.go
> +		response.SafeUser.FollowStatus = h.DB.GetFollowStatus(meId, userId)
Authenticated users don't get the `followStatus` if it's `0`

https://github.com/merpw/forum/assets/43277901/82fb294e-be85-4085-a62b-f4886d62f96a

2023-08-07 14:17 UTC, maximihajlov commented
I've just pushed 53d637440e9722ae0d89163c1ed90466f3af344c, which adds the fix of the bug in frontend that I found in my previous review. It can be used to check if `followStatus` in response is valid

2023-08-07 14:28 UTC, maximihajlov commented on backend/forum/handlers/users.go
> +	meId := h.getUserId(w, r)
Nevermind, `/users/{id}` is public, so context value might not be filled. Maybe we could add it for all requests later, but not in this PR.

2023-08-08 13:52 UTC, maximihajlov commented
Moved to #104

2023-08-08 13:54 UTC, closed without merging

2023-08-08 13:55 UTC, maximihajlov commented
Closed as moved to #104