Features/registration form
merpw/forum pull request #14
Opened 2023-04-04 20:48 UTC by nattikim

Review, please. Had to start it "from scratch". Previous branch has to be deleted.

2023-04-05 19:21 UTC, maximihajlov requested changes

2023-04-05 19:21 UTC, maximihajlov commented on backend/database/models.go
> +	Email     string
Looks like you did not test it on the existing database. Error 500:

![image](https://user-images.githubusercontent.com/43277901/230178490-39d7e42a-7fb6-40e6-85b6-5c1ba9080864.png)

Optional fields are NULLABLE, so they can not be saved to standard golang types. Use database types such as [`sql.NullString`](https://pkg.go.dev/database/sql#NullString) instead.

2023-04-05 19:21 UTC, maximihajlov commented on backend/server/handlers_auth.go
> +		FirstName string `json:"first_name"`
We should not always send optional fields. 
```json
{
    "id": 1,
    "name": "user",
    "email": "user@example.com",
    "first_name": "John",
    "last_name": "",
    "age": "",
    "gender": ""
}
```
Should be: 
```json
{
    "id": 1,
    "name": "user",
    "email": "user@example.com",
    "first_name": "John",
}
```

2023-04-05 19:21 UTC, maximihajlov commented on backend/database/models.go
> +	Age       string
Maybe age should be a number? And maybe it makes more sense to ask for the date of birth instead to keep the age up to date.

2023-04-05 19:21 UTC, maximihajlov commented on frontend/src/pages/me.tsx
> +        {"Gender: "} <span className={"text-2xl"}> {user?.gender} </span>
Also not sure about gender as a string. Maybe it's better to ask for preferred `pronouns` instead.

2023-04-05 19:21 UTC, maximihajlov commented on frontend/src/pages/signup.tsx
> +
All input fields are mostly the same. It's better to start creating custom tailwind classes now. 

Another option is not to store fields in an array of objects and generate it with for loop. Like [**here**](https://github.com/merpw/forum/blob/main/frontend/src/pages/me.tsx#LL60B1-L73C12):
```tsx
  const tabs = [
    { title: "Your posts", component: <UserPosts /> },
    { title: "Your liked posts", component: <UserLikedPosts /> },
  ]

 ...

<ul className={"flex flex-wrap gap-2 text-2xl mb-3"}>
        {tabs.map(({ title }, key) => (
          <li
            key={key}
            className={
              "cursor-pointer hover:opacity-60 p-1 " +
              (activeTab == key ? "border-b-2 border-b-blue-500" : "")
            }
            onClick={() => setActiveTab(key)}
          >
            {title}
          </li>
        ))}
</ul>
```

2023-04-10 15:37 UTC, sagarishere commented on backend/server/handlers_auth.go
> +		FirstName string `json:"first_name"`
all fields are required fields. right? 
![image](https://user-images.githubusercontent.com/5121817/230935304-f1ae6262-c763-4da7-ad18-ee99d5ccd8ba.png)

2023-04-17 17:02 UTC, maximihajlov requested changes

2023-04-23 16:01 UTC, nattikim commented on backend/server/test/get_test.go
@maximihajlov  maybe it should be done by those who's doing the tests?

2023-04-23 16:03 UTC, nattikim commented on frontend/src/styles/globals.css
> +    @apply my-1;
@maximihajlov this should be part of Design changes. In new branch

2023-04-24 18:09 UTC, maximihajlov requested changes

2023-04-24 18:09 UTC, maximihajlov commented on frontend/src/pages/create.tsx
No client-side validation for fields length and spaces (no trim)

2023-04-24 18:18 UTC, maximihajlov approved these changes

2023-04-24 18:35 UTC, merged