Features/database migrations
merpw/forum pull request #22
Opened 2023-04-11 13:44 UTC by maximihajlov

Adds a new `database/migrate` package to easily migrate between revisions (forward and backward).

Adds a `CLI` to migrate between revisions from the console.

Adds initial migration and migration to make all fields `NOT NULL`

## How to test?

- [ ] Make initial migration on the existing database (just start a new version of the server on the database created by the previous one)
- [ ] Check if all fields are `NOT NULL` 
- [ ] Try to migrate back to revision `1` (e.g. using `CLI`) 
- [ ] Check if all fields are not `NOT NULL`
- [ ] Add more migrations and migrate up and down, making sure that the database structure and data are not corrupted

@sagarishere @healingdrawing, it's good to improve tests for this package in #3

2023-04-11 17:15 UTC, healingdrawing commented on backend/database/migrate/README.md
> +2. Run `cli -h` to see the available commands
Add `./` before `cli -h`

2023-04-11 17:16 UTC, healingdrawing commented on backend/database/migrate/README.md
> +   - For example, `cli -db database.db stat` will show you the current revision of the `database.db` schema
Add `./` before command

2023-04-11 17:16 UTC, healingdrawing commented on backend/database/migrate/README.md
> +   - `cli -db database.db migrate latest` will migrate database to the latest available version.
Add `./` before command

2023-04-11 20:16 UTC, sagarishere requested changes

2023-04-11 20:16 UTC, sagarishere commented on backend/database/migrate/migrate.go
> +		log.Printf(`WARNING: migrating database DOWN from %d to %d
here one needs to input the "YES" and press enter. This is difficult to simulate in testing.
Kindly implement some bool parameter or global variable bypass for testing this function, and other functions like this if any more.

2023-04-11 20:24 UTC, maximihajlov commented on backend/database/migrate/migrate.go
> +		log.Printf(`WARNING: migrating database DOWN from %d to %d
Maybe it's not clear, but definitely possible (and not too difficult). There are no optional arguments in go so the only way to do that is to use an array of parameters, which looks terrible. I would prefer to test it as is. 

To do so you can create mock `os.Stdin` by replacing it with a temporary file (everything is a file, even `os.Stdin`)

2023-04-12 15:02 UTC, maximihajlov commented on backend/database/migrate/migrate.go
> +		log.Printf(`WARNING: migrating database DOWN from %d to %d
I think it's not golang-way to do it. It's not too hard to create mock `os.Stdin` as I said before. To do so you can use `os.CreateTemp`. It will create a temporary file that we will use to emulate `os.Stdin`:

https://go.dev/play/p/U-hcX8voLD2

2023-04-12 16:14 UTC, maximihajlov commented on backend/database/migrate/migrate.go
> +		log.Printf(`WARNING: migrating database DOWN from %d to %d
Implemented in d80077bdc081aa227f7b5cd64bea08258640440e

2023-04-12 18:36 UTC, healingdrawing approved these changes
nothing weird found

2023-04-12 18:42 UTC, merged