Database extension for chat
merpw/forum pull request #29
Opened 2023-04-20 17:58 UTC by sagarishere

Database has been extended for chat functionality development initial steps

2023-04-20 18:01 UTC, sagarishere commented
Good code by Sergei. I pass

2023-04-21 11:54 UTC, maximihajlov requested changes
The pull request is not ready for approval. There's a **harmful change** that breaks post reactions functionality and a lot of things that were discussed and supposed to be fixed. 

@sagarishere, merging your `backend-testing-improvements` branch to Sergei's `database-extensions-for-chat` was a mistake. Your improved tests are not related to chat functionality, so the whole concept of separate feature branches is broken. You had to open a pull request to the `main` branch instead.

It makes reviewing process much more complicated because all changes are in the same branch. You have also squashed changes that were not approved which makes it more complicated to `git blame` and see file-specific commit messages. Please be more thoughtful next time. 

It would be better to drop Sagar's merge commit in this branch and continue working in separate branches with two separate pull requests.

2023-04-21 11:54 UTC, maximihajlov commented on backend/server/handlers_posts_id.go
> -func (srv *Server) postsIdReactionHandler(w http.ResponseWriter, r *http.Request) {
## **HARMFUL CHANGE!**

Here's a perfect example of why tests are not complete. You just removed the whole post reactions functionality, but the tests are still passed...

https://user-images.githubusercontent.com/43277901/233619128-7aa285f5-6468-4b7a-b139-0f452b0aaf2e.mp4

2023-04-21 11:54 UTC, maximihajlov commented on backend/server/test/Readme.md
> +# Step by step guide to test coverage in Go
This guide is not related to the project. If we start adding instructions for all Go features that we used, this project will become Golang documentation. There are many guides online on how to run tests with coverage. If you believe, that one who wants to run tests with coverage cannot google, you can add a link to README or create a GitHub discussion.

2023-04-21 11:54 UTC, maximihajlov commented on backend/server/test/get_cover_report.sh
> +#!/bin/sh
This script is also not related to the project. If you want to make VSCode devs' lives easier, it makes more sense to implement run configuration to run tests with a single click. But for most users, it's easier to just set up VSCode once. 

https://dev.to/vuong/golang-in-vscode-show-code-coverage-of-after-saving-test-8g0

2023-04-21 11:54 UTC, maximihajlov commented on backend/server/test/get_test.go
> +func TestQueries(t *testing.T) {
This test is invalid and misplaced. This is `forum/server/test`. It should test `server`, not `database`. Database tests are implemented in `forum/database/test`. 

It is also invalid because it executes functions on a manually initialized database. In production. the database is initialized using `db.InitDatabase` which handles tables structure and migrations between revisions. 

Basic database tests are WIP by @healingdrawing in `forum/database/test`, so if you want these changes to be added, you have to move them to `database_test.

2023-04-21 11:54 UTC, maximihajlov commented on backend/server/test/get_test.go
> +	// Opens sqlite3
Avoid obvious comments. `Opens sqlite3` for `sql.Open` function is a completely useless comment as well as `connects server to DB, and initiates the DB` above `server.Connect` and `srv.DB.InitDatabase`.

2023-04-21 11:54 UTC, maximihajlov commented on .gitignore
> +# If you prefer the allow list template instead of the deny list, see community template:
No need for this global `.gitignore`, especially Golang-based. We already have local `backend/.gitignore` and `frontend/.gitignore` with language-specific rules.

2023-04-21 12:41 UTC, healingdrawing commented on backend/database/migrate/migrations/migrations.go
> +	v004,
because @maximihajlov already use the name `v003` in his branch `features/markdown`, and @healingdrawing noticed this before create the migration file

2023-04-21 12:51 UTC, maximihajlov commented on backend/database/migrate/migrations/migrations.go
> +	v004,
You don't have to care about other branches. This is a pull request to the `main` branch and there's no `v003` version in it yet. We don't know which feature is going to be merged first, so you should proceed from the current state of `main`. 

For example, in both branches `features/markdown` and `features/registration-form`, we use the same `v003` version. If `features/markdown` will be merged first, migration in `features/registration-form` will be changed to `v004` while resolving the merge conflict while merging/rebasing with `main`.  And vice versa.

2023-04-22 02:16 UTC, healingdrawing commented on backend/database/ops_chats.go
> +func (db DB) GetPrivateChatOponentsByUserId(userId int) []OnlineUser {
because user(with userId) is member too. So members list of chat where user is member includes user itself as member, but we need only other users (which is opponents of user in private chat) exclude user itself @maximihajlov

2023-04-22 02:33 UTC, healingdrawing commented on backend/database/test/ops_chats_test.go
> +	// add dummy user, without session, to check if it is ignored
@maximihajlov this "obvious" comment describes the next code part, but not the code above you select. Later this user will be used only to check the number of users in filtered query result, to confirm that filtering works(or try to confirm)

2023-04-22 03:15 UTC, healingdrawing commented on backend/database/test/database_test.go
> +	"forum/server"
i already tried this before, at the beginning, and fail , because when i just use instance of db, then, in some purposes all method declared as
`func (db DB) MethodName(` are not available. Only built in methods are available. And i just follow the syntax/way which is works, and allows me to use method which need to be tested.
![db](https://user-images.githubusercontent.com/39751647/233759034-c3a41893-7a10-4af8-a451-c4a725dcb2ca.png)

2023-04-22 11:11 UTC, maximihajlov commented on backend/database/ops_chats.go
> +func (db DB) GetPrivateChatOponentsByUserId(userId int) []OnlineUser {
- Op**p**onents is spelled with two `p`'s
- Name `Opponents` is not clear. `GetUserContacts` makes much more sense.
- `OnlineUser` has bad name and useless. For example, in this function we return all of the user's contacts, even if they are not online. It is more like `UserBase`, which may be part of the `User`. But it makes more sense to me to just use `User` like we do in `GetUserById`. 
- We did not discuss implementation of this function, there's no need to overcomplicate module with functions that can be avoided by using `GetUserChats` and `GetChat` (which is for some reason `GetAllMessagesByChatId`) right now. It may be added when we'll implement messages to get your contacts.

2023-04-22 11:13 UTC, maximihajlov commented on backend/database/ops_chats.go
> +func (db DB) GetPrivateChatsByUserId(userId int) []Chat {
Should be changed to more universal `GetUserChats` with `chatType` enum argument

2023-04-23 07:01 UTC, healingdrawing commented on .gitignore
> +# If you prefer the allow list template instead of the deny list, see community template:
this file needed. Every time folder opened using "reveal in finder" of just opened using finder navigation , garbage `.DS_Store`created. To prevent commit this , user should manually not include or exclude one file from changes every commit. global .gitignore allows to solve this easily once, for the whole project.

2023-04-23 08:11 UTC, healingdrawing commented on backend/database/test/database_test.go
> +	"forum/server"
perhaps will try using this syntax from @sagarishere 's `get_test.go` line `142` , next attempt.

```
// Call GetPostComments() with the ID of the test post
dbInstance := database.DB{DB: db}
comments := dbInstance.GetPostComments(1)
```

2023-04-25 19:01 UTC, maximihajlov requested changes
Review is not over, but several serious issues were found. 

Changes by @sagarishere are still not ready for production at all. A lot of irrelevant TODOs, commented-out parts of code, and just bad practices. And yeah, one more [**change that breaks functionality**](https://github.com/merpw/forum/pull/29#discussion_r1176834898).

The pull request is not ready for merging.

2023-04-25 19:03 UTC, maximihajlov commented on backend/bin/golangci-lint
resolved by me in f5d2b65

2023-04-25 19:04 UTC, maximihajlov commented on backend/database/models.go
> +	Type int // 2 (private 1vs1) or 1 (group chat) or 0 (the channel owner is posting to subscribers)
resolved in f5d2b65

2023-04-25 19:05 UTC, maximihajlov commented on backend/server/test/post_test.go
> +func getInvalidUsers() []TestUser {
resolved in f5d2b65

2023-04-25 19:05 UTC, maximihajlov commented on backend/server/test/post_test.go
> +type Post struct {
resolved in f5d2b65

2023-04-25 19:06 UTC, maximihajlov commented on backend/database/ops_chats.go
> +// AddMessage adds message to database, returns id of new message, plus updates last_message_date in chats table
resolved in f5d2b65

2023-04-26 13:35 UTC, healingdrawing commented on backend/server/regexps.go
> +// macthes /api/posts/ and /api/posts
Pattern should be flexible. This function only escaping "/" then compile regexp.

2023-04-26 13:41 UTC, healingdrawing commented on backend/server/test/get_test.go
> +	// Opens the available routes
can not find this

2023-05-18 13:53 UTC, sagarishere commented on .gitignore
> +# If you prefer the allow list template instead of the deny list, see community template:
@maximihajlov the first line of .gitignore file in golang open-source code.
<img width="999" alt="Screenshot 2023-05-18 at 16 48 19" src="https://github.com/merpw/forum/assets/5121817/985c9d0f-437b-475e-a440-fa96597808e5">

If a software developer has to have the global env setting always right, and also, is carefully to add the files which they are supposed to commit, there might not be need of a .gitignore in any project at all.

I think it prevents mistaken adding of some files, that's all.

2023-05-18 18:38 UTC, maximihajlov commented
Branch was spitted, backend testing improvements are now in #50. Database extension for chat is in `futures/chat-backend`. Typo by sergei ;)

2023-05-18 18:38 UTC, closed without merging