Features/design
merpw/forum pull request #56
Opened 2023-06-06 12:11 UTC by nattikim

Placeholders will be added later

2023-06-06 17:51 UTC, maximihajlov reviewed
The FORUM logo, gradient colors and the concept is great! 

But I have several comments

- Fonts are really hard to read, using `font-light`, `font-thin` and `text-sm` together is usually a bad idea. 

![image](https://github.com/merpw/forum/assets/43277901/77c764aa-d58b-42e5-b6dc-26f6f74f948a)

- Sometimes the contrast between foreground and background is not enough. Especially for the cool hand-written intro messages:

![image](https://github.com/merpw/forum/assets/43277901/67945a70-d031-453b-ba8a-b12dbfdd137e)

![image](https://github.com/merpw/forum/assets/43277901/7e8b2db4-c78d-4156-a198-49401e033cdc)

- Not sure about the background here

![image](https://github.com/merpw/forum/assets/43277901/f7152eb3-b0e7-47fc-9bf4-8212d539463b)

- AI button looks sad😢
![image](https://github.com/merpw/forum/assets/43277901/8cf71d2e-37d4-4534-bfd9-a4c4c8d7c329)

2023-06-06 18:10 UTC, maximihajlov requested changes

2023-06-06 18:10 UTC, maximihajlov commented on frontend/src/styles/font.css
> +  src: url("fonts/Alatsi-Regular.woff2") format("woff2");
Both new fonts are Google fonts. Next.js has a great [font optimization](https://nextjs.org/docs/app/building-your-application/optimizing/fonts) feature which improves performance and reduces layout shift. It's much better to use it instead.

2023-06-06 18:10 UTC, maximihajlov commented on frontend/src/app/error.tsx
> +            <span className={"my-1"}>
Reset button was accidently removed

2023-06-06 18:10 UTC, maximihajlov commented on frontend/src/app/category/[name]/category-page.tsx
> +            <span className={"ml-1 text-xs"}>Create a new post</span>
It's much better to use [shared layout](https://nextjs.org/docs/app/api-reference/file-conventions/layout) `category/layout.tsx` instead to prevent unnecessary renders.

2023-06-07 14:55 UTC, maximihajlov commented on frontend/src/app/user/[id]/user-page.tsx
> +                  "M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0
The icon is the same as for post creation. I think it's better to use bubble icon, like 💬

The chats are not implemented yet. So it's a 404 button

![image](https://github.com/merpw/forum/assets/43277901/da0b3b61-f38e-4eb8-859a-8d7cc4f4aafc)

2023-06-07 16:25 UTC, maximihajlov commented on frontend/src/app/me/user-page.tsx
> +      <div className={"flex flex-col self-center text-md font-thin mb-5 text-center sm:text-left"}>
There's no `text-md` in tailwind, but there's `text-base`

https://tailwindcss.com/docs/font-size

2023-06-07 17:56 UTC, maximihajlov commented on frontend/src/app/post/[id]/post-page.tsx
> +            <span className={"gradient-text font-black mx-1"}>•</span>
It's bad practice to have child elements for `h1` headings and to use `•` in them. This negatively affect SEO. It's much better to use css `:before` and `:after` for this (and maybe even implement a custom class for that, as we use these dots in several places)

2023-06-07 18:01 UTC, maximihajlov commented on frontend/src/styles/font.css
> +  src: url("fonts/Alatsi-Regular.woff2") format("woff2");
Fixed in f54b5d274386d48af233729d4ebd76e5902293e2

2023-06-07 18:01 UTC, maximihajlov commented on frontend/src/app/category/[name]/category-page.tsx
> +            <span className={"ml-1 text-xs"}>Create a new post</span>
Fixed in b42960f869aa9fb064a8ef99bb3c950ead03bd90

2023-06-07 18:15 UTC, maximihajlov commented on frontend/src/app/error.tsx
> +          <p className={"font-thin flex flex-col gap-1"}>
Does `font-thin` work for you? For me it's the same as `font-light`. Looks like the default font does not support weight `100`. But weight `300` looks good to me

2023-06-07 18:39 UTC, maximihajlov commented on frontend/src/app/create/create-page.tsx
> +            <FormError error={formError} />
`FormError` styles should be improved. Looks bad in dark theme with the the background:

![image](https://github.com/merpw/forum/assets/43277901/53dda7f7-60ec-48b2-8342-760d166e6fe8)

![image](https://github.com/merpw/forum/assets/43277901/f80c1880-6260-4608-aade-8d69d0747a5c)

2023-06-07 21:20 UTC, bomanviktor commented on frontend/src/app/post/[id]/post-page.tsx
> +            <span className={"gradient-text font-black mx-1"}>•</span>
As such:
![image](https://github.com/merpw/forum/assets/72476579/742f41e2-06f0-4360-81c2-345d750ec769)

2023-06-07 21:22 UTC, bomanviktor commented
This looks really nice, I agree with everything Maksim said. I am unable to do work from home right now so I will have a look at it at paf tomorrow.

2023-06-08 11:17 UTC, nattikim commented on frontend/src/app/user/[id]/user-page.tsx
> +                  "M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0
the icon has been changed
the chats will be linked to a button in a couple of days (hopefully), right now it directs to /chat endpoint as a placeholder

2023-06-08 16:28 UTC, bomanviktor commented
One more thing, I would also sort the categories in the same order in the posts as in the category selector:
<img width="792" alt="Screenshot 2023-06-08 at 19 27 32" src="https://github.com/merpw/forum/assets/72476579/fc382127-db6a-4354-aec5-83be89ab1197">

2023-06-13 18:23 UTC, bomanviktor commented
Scrap my previous comment about having to log in before having access to the forum. It seems to work now! I wonder why it didn't work previously.

Nice addition of show/hide pw. And awesome touch adding the link to the repo in the footer!

The wrong error message seems to be displayed on comments (string is 1824 characters long):
![image](https://github.com/merpw/forum/assets/72476579/b8226114-e039-46b7-9f91-b68c32a6bc8a)

Also, I think you forgot maxLength here:
```
// Inside CommentForm.tsx
          <ReactTextareaAutosize
            id={"comment-text"}
            className={"textarea textarea-bordered w-full"}
            value={text}
            onInput={(e) => setText(e.currentTarget.value)}
            required
            rows={1}
           // Probably add maxLength{length} here
          />
```
Also it would be nice if the posts were updated when the user creates a new post and clicks on the home button, right now they would have to refresh the page.

2023-06-14 14:28 UTC, maximihajlov requested changes
Almost everything looks good to me, just two small comments about buttons

2023-06-14 14:28 UTC, maximihajlov commented on frontend/src/app/user/[id]/user-page.tsx
> +          <span className={"ml-1 text-xs"}>{"Let's chat!"}</span>
I think icon should be moved to the left like in all other buttons.

And the chats are not implemented yet, so it's better to comment it out and uncomment in the future `chat-frontend` pull request.

![image](https://github.com/merpw/forum/assets/43277901/f37e19d9-551c-4d54-8934-820470963cba)

2023-06-14 14:28 UTC, maximihajlov commented on frontend/src/app/create/create-page.tsx
> +                Generate description
Hard to read in dark theme, maybe make bolder or add text outline/shadow?

![image](https://github.com/merpw/forum/assets/43277901/c0e410ef-a927-4637-a2d6-3ba60cd68654)

2023-06-14 14:42 UTC, maximihajlov commented
> The wrong error message seems to be displayed on comments (string is 1824 characters long)

Yeah, max length is 1000, not 10000. This pull request is about the design, so this bug should be fixed in another pull request.

> Also it would be nice if the posts were updated when the user creates a new post and clicks on the home button, right now they would have to refresh the page.

This is a feature, not a bug :)

The main page is pre-fetched after initial load, before user creates the post. This makes navigation instant. Right now the whole home page is server-side rendered. Of course, we can call [`router.prefetch("/")`](https://nextjs.org/docs/app/api-reference/functions/use-router#:~:text=router.prefetch(href%3A%20string)%3A%20Prefetch%20the%20provided%20route%20for%20faster%20client%2Dside%20transitions.) to pre-fetch again the updated version of the homepage after post creation, but I think it's better to implement client-side post data fetching instead, like we do for comments. This wlll be a part of #52.

2023-06-16 07:57 UTC, maximihajlov commented on frontend/src/app/user/[id]/user-page.tsx
> +          <span className={"ml-1 text-xs"}>{"Let's chat!"}</span>
Button is good now, but it was not commented out

2023-06-16 08:14 UTC, maximihajlov commented on frontend/src/app/create/create-page.tsx
> +                  "btn btn-sm transition-none hover:opacity-100 hover:gradient-text hover:saturate-200 hover:border-primary btn-outline font-light mb-3 self-center font-xs hover:drop-shadow-2xl outli
Correct me if I'm wrong, but looks like `outline-8` and `outline-red-600` do not work. 

Outline in this context is button outline. And it does not work, because there's no outline-style set. If set to solid, here's how it looks like :)

![image](https://github.com/merpw/forum/assets/43277901/751f7279-d8e8-411a-b254-6bdc4a690677)

In my review I was talking about **text** outline. If we want to show colored and `font-light` text on a dark background, we have to add some outline/border to make it easier to read. 

There's no outline css rule for text, but there's drop shadow, which may look like this:
![image](https://github.com/merpw/forum/assets/43277901/e874655c-c379-427f-8271-ba9b3912d035)

Here's an example of how it can be done with Tailwind:
https://stackoverflow.com/a/74753353

2023-06-16 08:18 UTC, maximihajlov commented on frontend/src/app/create/create-page.tsx
> +                  "btn btn-sm transition-none hover:opacity-100 hover:gradient-text hover:saturate-200 hover:border-primary btn-outline font-light mb-3 self-center font-xs hover:drop-shadow-2xl outli
It's really hard to refactor unused tailwind rules in future, because there's no IDE highlighting for such things. So please, check if all rules you add make sense and work 🙃

2023-06-16 14:05 UTC, nattikim commented on frontend/src/app/create/create-page.tsx
> +                  "btn btn-sm transition-none hover:opacity-100 hover:gradient-text hover:saturate-200 hover:border-primary btn-outline font-light mb-3 self-center font-xs hover:drop-shadow-2xl outli
my bad, forgot to remove my previous experiments.

the shadow could look good on bigger and bolder text, otherwise it make the text looks blurry which doesn't make it easier to read.

I'll just change font weight to normal, I think that's enough for the text on the button which appears only on hover (it usually being read before you decide to hover on it)

<img width="650" alt="Screenshot 2023-06-16 at 16 58 48" src="https://github.com/merpw/forum/assets/93912586/df2bd5f3-ce1b-4c2b-9b87-f1c0e25b4f1c">
<img width="655" alt="Screenshot 2023-06-16 at 16 59 13" src="https://github.com/merpw/forum/assets/93912586/763b9172-aab7-400d-8265-305e6801c8c1">

2023-06-16 20:21 UTC, maximihajlov approved these changes
That's one small step for @nattikim, one giant leap for our project! Great job, the design now looks much cooler.😎

LGTM👏

2023-06-17 10:07 UTC, bomanviktor approved these changes
I would still add a solid background to the posts in the post list. But other than that it looks good!

2023-06-17 12:12 UTC, merged