Features/chat frontend design
merpw/forum pull request #74
Opened 2023-07-05 19:50 UTC by nattikim

2023-07-13 16:58 UTC, maximihajlov requested changes
Good job!👏 The design looks great. 

I've added a few little comments and one proposal, it's almost ready for merge!

2023-07-13 16:58 UTC, maximihajlov commented on frontend/src/components/chats/section/ChatList.tsx
> +      <div className={"flex justify-end text-info text-xs font-light mt-1"}>
We've already discussed it in #56. Please, don't use `text-xs` and `font-light` at the same time. It makes the text hard to read 🤓

2023-07-13 16:58 UTC, maximihajlov commented on frontend/src/components/chats/MessagesDateGroups.tsx
> +              "z-50 text-xs text-info bg-primary bg-opacity-10 backdrop-brightness-200 dark:backdrop-brightness-50 backdrop-blur-sm px-3 rounded-xl" +
Paddings are not the same, idk why

![image](https://github.com/merpw/forum/assets/43277901/6e90d351-776a-411a-b6bf-d26112fbfefd)

2023-07-13 16:58 UTC, maximihajlov commented on frontend/src/components/chats/section/UserList.tsx
> +      <Link
I think it makes sense to make the whole button clickable, like we already do in ChatList. Otherwise the most important `chat` button is too small. 

![image](https://github.com/merpw/forum/assets/43277901/d10c2fff-ff8f-4ed0-8bc1-735cfe9b8afd)

2023-07-13 16:58 UTC, maximihajlov commented on frontend/src/components/userInfo.tsx
> +            <Avatar userId={user!.id} />
`Forbidden non-null assertion` warning from eslint here. It's safer to add additional if statement instead to make sure that user is not null.

```tsx
if (!user) {
   return null
}
```

2023-07-13 18:33 UTC, nattikim commented on frontend/src/components/chats/section/ChatList.tsx
> +      <div className={"flex justify-end text-info text-xs font-light mt-1"}>
we've been talking about font thin. which was changed to font light

2023-07-13 18:51 UTC, nattikim commented on frontend/src/components/chats/MessagesDateGroups.tsx
> +              "z-50 text-xs text-info bg-primary bg-opacity-10 backdrop-brightness-200 dark:backdrop-brightness-50 backdrop-blur-sm px-3 rounded-xl" +
tiny loss in rebasing battle:) padding is returned to it's place now

2023-07-13 19:10 UTC, nattikim commented on frontend/src/components/chats/section/UserList.tsx
> +      <Link
It's good idea to make all the area clickable but not sure what's more important in such list the username with link to user profile (where is also another chat button) or this chat button..

Imagine you open user list with users you don't know and haven't chat before, there is much higher chance that you first would want to go to their profile page, not to chat with them right away. If you do know them and/or did chat with them, you most likely will go to the chat through chat list.

In case of less common cases (if you don't care who is the person and just want to drop a message) there is the button (even if small). Do not forget, there will be also "follow" icon button right next to it and maybe some more.. so the space will get more crowded

2023-07-13 19:50 UTC, nattikim commented on frontend/src/components/chats/section/UserList.tsx
> +      <Link
I've made the empty space leading to profile for now

2023-07-13 21:00 UTC, maximihajlov commented on frontend/src/components/chats/section/UserList.tsx
> +    return <div className={"text-info text-center mt-5 mb-7"}>loading...</div>
The `loading...` placeholder causes layout shift here

https://github.com/merpw/forum/assets/43277901/15d2282c-2263-4033-a429-f7d0a0318801

2023-07-14 14:37 UTC, maximihajlov requested changes
The scroll is broken

https://github.com/merpw/forum/assets/43277901/a0765f02-9bce-4fee-8c9b-884b19601cb6

2023-07-14 15:53 UTC, maximihajlov requested changes

2023-07-14 15:53 UTC, maximihajlov commented on frontend/src/components/chats/ChatMessages.tsx
> +      className={"overflow-y-auto h-full flex flex-col-reverse"}
This breaks scroll to bottom when resizing the input box:


https://github.com/merpw/forum/assets/43277901/0b7276af-a059-486f-b4ac-23a0e8edee7d

2023-07-14 16:01 UTC, maximihajlov commented on frontend/src/components/chats/ChatMessages.tsx
> +      className={"overflow-y-auto h-full flex flex-col-reverse"}
As I mentioned [before](https://github.com/merpw/forum/pull/56#discussion_r1231939079), it's really hard to refactor unused tailwind rules in the future. Please make sure that all rules you add are useful. `flex and flex-col-reverse` are useless in this case, because `scrollRef` has only one child.

2023-07-14 17:05 UTC, maximihajlov approved these changes
LGTM!🎉 Good job👏

2023-07-14 17:20 UTC, merged

2023-07-29 20:32 UTC, bomanviktor commented
Brilliant job!! Sorry I was AWOL. Got hyperfocused on vanilla-frontend but this looks so sweet.