Add `./start.sh`
merpw/forum pull request #77
Opened 2023-07-06 23:19 UTC by maximihajlov

This pull request adds a new `./start.sh` script, which makes starting the project even easier than `docker compose`.

Instead of building the whole project every time, it's now possible to just pull a specific revision of Docker images from the GitHub Container Registry.

For example, to run the `latest` revision (the one that is deployed to https://forum.mer.pw), we can now just call:

```bash
./start.sh
```

Another important update is that the pull request review process was significantly simplified. When one opens a pull request, the docker image is built. We did not use this image before, but now we do!

```
./start.sh pr-76
```

E.g. this simple command starts the docker compose with images that were built in pull request 76. It’s much faster and easier than building all the services locally.

2023-07-08 13:37 UTC, nattikim requested changes
the revision build does not work, it doesn't find revisions, i've tried few.. so as expected the main being build (forum-ci one).
plus I had to change permissions manually 
<img width="1651" alt="Screenshot 2023-07-08 at 16 03 50" src="https://github.com/merpw/forum/assets/93912586/eb11a737-c40b-457e-bfc7-3d56d6978f43">

2023-07-08 13:51 UTC, maximihajlov commented
> the revision build does not work

Our target architecture is `x86`, so we build and deploy our images with this architecture. As I see you are using Apple silicon Mac, which uses `arm64`. 

I see two possible solutions:

- [Enable `Rosetta 2` virtualization feature](https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5) in your docker desktop. This will enable Apple's "emulator" for `x86` and will allow you to run our images locally.

- Build images to `arm64` using `docker compose up` or `./start.sh local`. But in this case your local image won't be the same as one that we deploy.

2023-07-08 18:48 UTC, maximihajlov commented
I've added `platform: linux/amd64` to our docker compose files, so now your Mac should build images in the right architecture. I've also improved `./start.sh` to use `docker compose pull` instead of `docker pull`. This should pull the version with right architecture, so you won't get any `no matching manifest` errors. I've just tested in on M1, everything works fine.

2023-07-09 13:49 UTC, nattikim approved these changes

2023-07-09 13:59 UTC, merged