vanilla-frontend
merpw/forum pull request #81
Opened 2023-07-11 12:42 UTC by bomanviktor

**Pull request for functionality of vanilla-frontend:**

It is obviously made entirely in plain JavaScript, without any external imports.

Differences in functionality:
- No implementation of profiles.
- No implementation of descriptions. (they are just saved as title + content)
- Posts are displayed in a feed, they do not have their own pages.
- Due to this feed layout, the length of posts and comments have been greatly reduced. (Could probably increase with a "read more" button).
- Chats are being created upon logging in, I am aware that this will send unnecessary requests.
- The nginx and docker has not been set up, yet.
- To run the program, simply run all the services separately. (backend/forum && go run . + backend/chat && go run . + vanilla-frontend && npx tsc -w).
- handlers.go has been slightly changed to enable serving of the public directory.

Point 1-3 will not change. Point 4 and 5 could change. The rest will be changed before submitting the project.

The structure of the project is as follows:
Upon entering the website, main.ts will check if the user has a cookie that is valid (I don't know if you could manually set a cookie, but can fix this if it's possible).

Content is displayed through the Auth function, which just takes true or false. If true, display the forum and run all handlers (ws, Me etc.), if false, display the login page and close the ws connection if it is open.

As you will see, the WebSocket implementation is kinda shady, since I started building it without postman I basically had no idea what was going on behind the scenes, I just had to build it with trial and error and reading through the typescript WS server by  @maximihajlov.

Last commits were basically me trying to clean up the messy code (it is still kinda messy though). I realized I could do a bunch of things better 80% through the project but I am in too deep to change it in an efficient manner (most notably: the creation of chats, the lazy loading doesn't go through the ID array but the actual messages array, setTimeout is being used 🤮)

 Please tell me what you think!

2023-07-11 14:25 UTC, maximihajlov requested changes
The branch should be rebased onto `main`. To simplify development and testing the backend should be the same as for Next.js frontend, so should not be changed in this pull request.

2023-07-11 14:25 UTC, maximihajlov commented on backend/chat/chat.db
Looks like you accidently committed the databases😅. Please be careful next time, maybe it's better to manually check the files and changes instead of `git add .`

As I see the `.gitignore` was moved to `forum` in #55. It should be moved back to prevent such problems in future.

2023-07-11 14:25 UTC, maximihajlov commented on backend/forum/handlers/handlers.go
> +		server.NewRoute(http.MethodGet, `/api/user/(\d+)`, h.usersId),
Please rebase the branch onto `main` and drop all the commits that already exist in `main`

2023-07-11 14:25 UTC, maximihajlov commented on backend/forum/handlers/test/cover_reports/coverage.html
This should not be added to git

2023-07-11 14:25 UTC, maximihajlov commented on backend/forum/handlers/test/get_cover_report.sh
This script is not a part of the project, so we've moved it to #32

2023-07-11 14:25 UTC, maximihajlov commented on nginx.conf
> -# TODO: maybe add "server started at" message;
Please avoid such commits to make the history cleaner🙄

2023-07-12 14:15 UTC, bomanviktor commented on .idea/.gitignore
> +# Default ignored files
It was an oversight by me, I did not notice it before I pushed it. Will be removed in next commit.

2023-07-12 14:16 UTC, bomanviktor commented on backend/chat/chat.db
Yeah! I will use WebStorm for all future git-related things. It was much better than the CLI.

2023-07-12 14:19 UTC, bomanviktor commented on backend/forum/handlers/test/get_cover_report.sh
Oh, this is me trying to run the tests in the CLI without success, they do not update as they did before. I will add them to .gitignore

2023-07-13 12:17 UTC, maximihajlov commented on backend/chat/chat.db
`chat.db` is still here

2023-07-13 12:23 UTC, maximihajlov commented on backend/forum/handlers/auth.go
Backend should not be changed at all in this pull request. You can easily see which files has changed [here](https://github.com/merpw/forum/pull/81/files). 

The backend CI is also watching for any changes, so even such small non-functional changes cause rebuilding and redeployment of the whole backend. As the backend should not be changed in this pull request, there should be no backend CI calls.

2023-07-13 12:24 UTC, maximihajlov commented on backend/server/test/cover_reports/coverage.html
Still not removed

2023-07-13 12:25 UTC, maximihajlov commented on nginx.conf
> -# TODO: maybe add "server started at" message;
Still here 🙈

2023-07-13 12:37 UTC, maximihajlov commented on vanilla-frontend/src/components/chat/helpers.ts
> +const throttle = (cb: Function, delay = 1000): Function => {
This function is not type-safe and the eslint warning was right. 

```ts
  // lazyLoading of messages
  export const lazyLoading = throttle((chatId: number): void => {
    // ...
  })

  // no errors even though string is not a number
  lazyLoading("no type safety") 
```
 
You can use mine which uses generics to provide this type safety:

https://github.com/merpw/forum/blob/7282cb577e4db67ad49c07537a71b9e20a25d7f8/frontend/src/helpers/throttle.ts#L1-L23

```ts
 // lazyLoading of messages
 export const lazyLoading = throttle((chatId: number): void => {
    // ...
  })

// TS2345: Argument of type 'string' is not assignable to parameter of type 'number'
lazyLoading("no type safety")
```

2023-07-13 12:38 UTC, maximihajlov commented on vanilla-frontend/src/components/chat/helpers.ts
> +const throttle = (cb: Function, delay = 1000): Function => {
And it's a good practice to move helper functions to a separate file

2023-07-13 13:01 UTC, maximihajlov commented on vanilla-frontend/package.json
> +    "tsc": "^2.0.4",
![image](https://github.com/merpw/forum/assets/43277901/b824be12-44ec-4362-8721-4c51882b1da7)

There's an error when running. `tsc` package conflicts with `typescript`. You should `npm remove tsc`.

2023-07-13 13:01 UTC, maximihajlov commented on vanilla-frontend/package.json
> +    "tsc": "^2.0.4",
![image](https://github.com/merpw/forum/assets/43277901/97a9e1d1-27b5-4379-a129-41f757c62785)

There're some vulnerabilities in eslint. `npm update` should fix the problem

2023-07-13 13:14 UTC, bomanviktor commented on vanilla-frontend/package.json
> +    "tsc": "^2.0.4",
Nice, I was having problems with this since I accidentally installed the wrong tsc.

2023-07-13 13:20 UTC, bomanviktor commented on vanilla-frontend/src/api/post.ts
> +/* IMPORTS */
I agree. I just thought it would be a good idea to conform to the common practice of grit:lab to comment more rather than less. I can remove this though of course.

2023-07-13 13:23 UTC, bomanviktor commented on backend/chat/chat.db
Lol I will just add all db files in gitignore.

2023-07-13 13:43 UTC, bomanviktor commented on vanilla-frontend/src/components/chat/helpers.ts
> +const throttle = (cb: Function, delay = 1000): Function => {
Also, you mean move helper functions into separate files inside a directory called helpers?

2023-07-13 13:59 UTC, bomanviktor commented on nginx.conf
> -# TODO: maybe add "server started at" message;
The nginx.conf is identical as the one in main, no? I don't understand this problem. Is there a commit that only contains this?

2023-07-13 14:07 UTC, bomanviktor commented
Maybe it would be a better idea to remove everything that is not vanilla-frontend from the pull request to avoid conflicts, as the backend is mostly used for development purposes until this gets merged? Or is it a better practice to also have everything in main (including next.js frontend) in the pull request?

2023-07-13 14:29 UTC, maximihajlov commented on backend/chat/chat.db
It's not enough. When the file was already added to git, .gitignore won't remove it

2023-07-13 14:31 UTC, maximihajlov commented
> Maybe it would be a better idea to remove everything that is not vanilla-frontend from the pull request to avoid conflicts

Remove where? Pull requests work with commits, not files. The problem that I described before is in that you have **commits** that change backend and frontend. They are not for the development, most of them are accidently pushed databases and other files that should not be committed. 

You don't have to touch or remove any files related to Next.js frontend and backend as they are not a subject of this pull request. The only thing you should do is it to make sure that you don't push any commits that change backend or frontend. https://github.com/merpw/forum/pull/81/files shows all files that are affected by your commits, so you can see which commits change these files and drop them

2023-07-13 14:47 UTC, bomanviktor commented on nginx.conf
> -# TODO: maybe add "server started at" message;
Oh, I see now. My bad 😂

2023-07-17 15:50 UTC, maximihajlov requested changes
- Lazy loading does not work

https://github.com/merpw/forum/assets/43277901/40103e93-49a2-41b3-86b6-d4d3de82f21b

- No notifications about new messages

> Open two browsers (ex: Chrome and Firefox), log in with different users in each one and with one of them try to send a private message to the other.
> 
> **Did the other user receive a notification?**

Chat section can be collapsed, in this case users won't see that they have a new message. 

I'm also not sure if it's good idea to make online and offline users sections collapsible (and collapsed by default)

2023-07-17 16:13 UTC, maximihajlov commented
I also recommend you to learn more about [commit guidelines](https://cbea.ms/git-commit/). 

The `subject` of commit is extremely important and should be informative. You have several commits with subject `Fixed:` or `Changes:`. This makes working with commits much harder as one has to open commit details to see what is the commit about. 

I also see that you have a lot of commits that are just fixing your own previous commits. It's good practice to remove (squash) all of these spam commits before sending it to the review to make it much easier to read and make the history cleaner.

We use imperative form in our commit messages. Most people use present tense as the git official documentation [suggests](https://stackoverflow.com/a/3580764). It's better to use the same tense for all commits for clarity and consistency.

2023-07-17 19:50 UTC, bomanviktor commented
> * Lazy loading does not work

Oversight by me, I switched the old throttle function without type safety to yours with type safety. Apparently it does not throttle my lazyloading function.

>  bandicam.2023-07-17.18-38-18-813.mp4 
> * No notifications about new messages
> 
> > Open two browsers (ex: Chrome and Firefox), log in with different users in each one and with one of them try to send a private message to the other.
> > **Did the other user receive a notification?**
> 
> Chat section can be collapsed, in this case users won't see that they have a new message.
> 
> I'm also not sure if it's good idea to make online and offline users sections collapsible (and collapsed by default)

Okay I can make it so that the chat section is **always** visible. I view it that they did recieve a notification (which will be visible once chat has been opened).

2023-07-18 14:09 UTC, nattikim requested changes
I think we can close our eyes on UI quality in this case ⚖️

But it worth to at least **add the user's name** somewhere, like greeting with username. If you have few accounts (and auditors will), it is very confusing since you can't check which account you're logged in atm.


The user list. There is no point to break it on two sections for online and offline users, it actually can be a problem.. because all the sorting gets messed up. 
In the example bellow "new0" supposed to be at the bottom of the list, but  it's on top of the list of offline users because there is new message been sent to that user, but it's unclear without any indication of it..
We also have requirement that chat with the latest sent message should be on-top of the list, but if you f.e. have messages from online users and then sending message to offline user, it will indeed be on-top of offline user list but still will be under online list..
It is better to **break the section into Chats and Users lists**.

<img width="206" alt="Screen Shot 2023-07-17 at 20 06 58" src="https://github.com/merpw/forum/assets/93912586/089a1265-ee79-4489-9b5b-697b93df4dd8">

2023-07-19 15:36 UTC, bomanviktor commented
I am underway of refactoring the entire websockets (including UI). 

What will be removed:
- Ability to collapse/expand the list of chats (no room for misinterpretation)
- Ability collapse/expand the "online/offline" sections.

What will be changed:
- I will have an object oriented structure with getters and setters.
- The data flow will be determined by events that will be dispatched. (IE: I get message ids from chat[id], dispatch event once ws.send has been called on all required Ids. This event renders the chat with the messages.)
- I might also change the "online/offline" sections to "online users/chats", so it works the same as yours. But this is only if I am done by tonight!

 Thanks for the feedback and pointing out the bugs. I wish I did the pull request sooner for earlier feedback.

2023-07-29 23:10 UTC, maximihajlov requested changes
Good job! Much better than before. But there're still several problems that might fail us on the audit.

2023-07-29 23:10 UTC, maximihajlov commented on vanilla-frontend/src/components/chat/client.ts
> +  private get sortedChats(): Chat[] {
We should probably add a separate all users sections to prevent failing one of the audit questions

> Are the chat users organized in alphabetic order?

Now they are sorted by the last message id. 

![image](https://github.com/merpw/forum/assets/43277901/5852cae5-6c8e-4d20-a20c-273e058ac685)

2023-07-29 23:10 UTC, maximihajlov commented on README.md
> +
🙃

2023-07-29 23:10 UTC, maximihajlov commented on .gitignore
> +.idea
Maybe it's better to add .idea to the global .gitignore on your machine instead

2023-07-30 08:53 UTC, bomanviktor commented on vanilla-frontend/src/components/chat/client.ts
> +  private get sortedChats(): Chat[] {
They are sorted alphabetically :)

2023-07-30 08:55 UTC, bomanviktor commented on vanilla-frontend/src/components/chat/chat.ts
> +    this.chatMessages.addEventListener("scroll", this.lazyLoading)
Nice catch

2023-07-30 10:26 UTC, maximihajlov commented on vanilla-frontend/src/components/chat/client.ts
> +  private get sortedChats(): Chat[] {
🤔

max, new, cat, alien...

Maybe the list of online users is sorted alphabetically, but the chat list is not

2023-07-30 16:19 UTC, nattikim commented on vanilla-frontend/src/components/chat/client.ts
> +  private get sortedChats(): Chat[] {
> We should probably add a separate all users sections to prevent failing one of the audit questions

agree.. user disappears from Online users list as soon as you start chat with the user..
<img width="199" alt="Screen Shot 2023-07-30 at 18 51 58" src="https://github.com/merpw/forum/assets/93912586/8e744931-abf5-4cdf-a088-784913873c99">

And unfortunately sorting seems does not work.. 🤔
<img width="208" alt="Screen Shot 2023-07-30 at 19 06 27" src="https://github.com/merpw/forum/assets/93912586/a11a9386-5842-4b5b-ba86-80e76ae32750">
<img width="199" alt="Screen Shot 2023-07-30 at 19 04 12" src="https://github.com/merpw/forum/assets/93912586/3aec7332-97b1-4508-bd90-b4a1132a88d6">

2023-07-30 16:36 UTC, bomanviktor commented
What steps did you take to make the online users unsorted? I guess it can
happen if you log in, and register multiple accounts.

In audit it specifies online users so I will only have that.

On Sun, Jul 30, 2023, 7:19 PM Natalia Kim ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In vanilla-frontend/src/components/chat/client.ts
> <https://github.com/merpw/forum/pull/81#discussion_r1278588111>:
>
> > +      setTimeout(() => {
> +        new List(this.onlineUsers, this.sortedChats, this.chatUserIds)
> +      }, 100)
> +    })
> +  }
> +
> +  reset() {
> +    this.activeChat = null
> +    this.chatIds = undefined
> +    this.chats.clear()
> +    this.messages.clear()
> +    this.userChats.clear()
> +    this.usersOnline = undefined
> +  }
> +
> +  private get sortedChats(): Chat[] {
>
> We should probably add a separate all users sections to prevent failing
> one of the audit questions
>
> agree.. user disappears from Online users list as soon as you start chat
> with the user..
> [image: Screen Shot 2023-07-30 at 18 51 58]
> <https://user-images.githubusercontent.com/93912586/257062583-8e744931-abf5-4cdf-a088-784913873c99.png>
>
> And unfortunately sorting seems does not work.. 🤔
> [image: Screen Shot 2023-07-30 at 19 06 27]
> <https://user-images.githubusercontent.com/93912586/257062801-a11a9386-5842-4b5b-ba86-80e76ae32750.png>
> [image: Screen Shot 2023-07-30 at 19 04 12]
> <https://user-images.githubusercontent.com/93912586/257062805-3aec7332-97b1-4508-bd90-b4a1132a88d6.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/merpw/forum/pull/81#discussion_r1278588111>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARI6PI4PCSMKCJXSPADZYE3XS2CQBANCNFSM6AAAAAA2F6NJ6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-30 17:32 UTC, nattikim commented
Registered and logged in new users that's all I did 🤷🏻‍♀️

2023-07-31 13:50 UTC, maximihajlov requested changes
Lazy loading is still not working for me

https://github.com/merpw/forum/assets/43277901/76778bff-13c7-418a-8283-d5b3cb09aa89

2023-07-31 14:38 UTC, nattikim approved these changes
LGETM 🎊

2023-07-31 15:26 UTC, nattikim reviewed
![It's alive!](https://y.yarn.co/b2fed38c-064f-493a-893b-9c6e8b222495_text.gif)

2023-07-31 15:53 UTC, merged