READMEs
merpw/forum pull request #89
Opened 2023-07-19 16:21 UTC by nattikim

This commit updates READMEs to edit co-authors (Maksim, Natalia, Sagar and Viktor), fix link to real-time-forum task and change the date of project release.
Also slight edition of migrate instructions of using actual migrations and database.

2023-07-19 19:05 UTC, maximihajlov requested changes

2023-07-19 19:05 UTC, maximihajlov commented on backend/forum/README.md
> -# backend/forum
`backend/forum` looks better to me. It's a name of the package, so one can `go run backend/forum`. The name of the docker images is still `forum` and I don't see a point in renaming it to `real-time-forum`.

2023-07-19 19:05 UTC, maximihajlov commented on frontend/README.md
> -# FORUM-FRONTEND
maybe it's better to rename it to just `frontend` as it's already in the `forum` repo (like we do in backend, which is just `backend/chat`.

2023-07-19 19:05 UTC, maximihajlov commented on backend/chat/README.md
same here, the name of the package is `backend/chat`, one can `go run backend/chat`

2023-07-19 19:14 UTC, maximihajlov commented on README.md
> -Solved during studying in Gritlab coding school on Åland, January 2023
Maybe leave just 2023, it's a bit annoying to change it every several months 😅

2023-07-21 14:26 UTC, nattikim commented on README.md
How it is forum when it's real-time-forum? there is different requirements for these two projects as well as changes in co-authors list? and later on it can be renamed to social-network

2023-07-24 11:04 UTC, maximihajlov commented on README.md
There's a difference between the **task** name and the **project** name. We're continuously developing the same project, and the name (working title) of this project is `forum`. We use it as a name of the repo, in docker images and in our logo. It's much more beautiful than `real-time-forum`, `typing-in-progress` or `social-network`, and there's no need to rename it in my opinion.

We have [releases](https://github.com/merpw/forum/releases) to mark different revisions of the project which correspond to different tasks. If you want, you can write about this in Readme.

2023-07-30 15:04 UTC, nattikim commented on README.md
no thanks

2023-07-31 12:37 UTC, maximihajlov commented on backend/forum/README.md
> +> I want to change some of the structures, how should I handle migrations?
We already have this FAQ in [`backend/migrate`](https://github.com/merpw/forum/tree/README-update/backend/migrate). Link should be enough

2023-07-31 12:55 UTC, maximihajlov commented on backend/forum/README.md
> +> I want to change some of the structures, how should I handle migrations?
Fixed in 9436e77

2023-07-31 13:21 UTC, merged